name: Run Spider

# 触发条件：每天早上6点 + 手动触发
on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  run-spider:
    runs-on: ubuntu-latest

    env:
      ENV: prod
      DJANGO_SETTINGS_MODULE: backend.settings
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      # 1️⃣ 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4️⃣ 执行数据库迁移
      - name: Apply Django migrations
        run: |
          python manage.py migrate

      # 5️⃣ 运行爬虫脚本并写日志
      - name: Run spider script
        run: |
          python spiders/run_all.py
      - name: Run wordcloud script
        run: |
          python splitwords/app.py
